### ISSUE TITLE
ROADMAP of things which need to be fixed

### ISSUE THREAD

**Issue by iamDyeus** [iamDyeus/CodTubify#7]
- [ ] Make a Installer for easily setting up the player for Use
- [ ] Fix the Player : It needs a new mechanism for Playing next Song.
- [ ] Fix Missing Font Imports
- [ ] To Find Alternative for FFmpeg and stuff (for reducing the apps size)
